### ISSUE TITLE
How does the LLVM backend function?

### ISSUE THREAD

**Issue by fmckeogh** [TI-Planet/Project-Builder#1]
I am trying to build a local Clang/LLVM C compiler for my TI84 Plus CE-T. I have successfully compiled Clang with a Z80 target using jacobly’s llvm-ez80, but I don’t understand the rest of the build process. Looking at “Backend.php”, I can see a call to run an “llvm” executable, but I don’t know if this a shell script with a full build system or a separate program.

TL;DR: How would I go about replicating the Project Builder’s LLVM backend locally?

Thanks!

**Comment by adriweb** [comment]
@debrouxl and I are working to make the PB easy to install/use in a local instance (although not for a few weeks now, we've both been busy :P). You can see some things in [setup](https://github.com/TI-Planet/Project-Builder/tree/master/setup).

That said, here's an overview of how it's working right now on TI-Planet's server:

The Backend registers a sh "builder script" [here](https://github.com/TI-Planet/Project-Builder/blob/master/modules/native_eZ80/Backend.php#L28) (which is, IIRC, the only file left not made public in this repo...) As you can see in [NativeBasedBackend.class.php#L39](https://github.com/TI-Planet/Project-Builder/blob/master/modules/NativeBasedBackend.class.php#L39) it's called via `sudo -u` (you may have to set sudoers rules with `visudo` to allow a practical use of that).

This builder knows a few actions, among which `llvm` and `llvmbuild` for compiling (calling clang) and building (calling clang, then calling the rest of ZDS tools on the output) respectively.
The short version of what's happening there is that it's sourcing a file to setup env vars:
```bash
...
export CEDEV=/opt/CEdev
export PATH=/opt/llvm/build/Debug/bin:/opt/CEdev/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
 and then calls `make` inside the project folder with some usual overrides:
```bash
make EXTRA_CFLAGS=\"${extraParams}\" USE_FLASH_FUNCTIONS=${useFlashFunctions} TARGET=${prgmName} L=\"${libsformake}\"" >> $logFile 2>&1
```
All that with some additional checks, user options fetching, and more pre/post-processing but you may not have to do all of that locally yourself, however.
The Makefile is a standard install of [CE toolchain's](https://github.com/CE-Programming/toolchain) patched only lightly (more or less something [like that](https://gist.github.com/adriweb/012b1e4ef705cbedd29b8a37916e95c2) from what I have here, I guess it needs updating for a patch applying to upstream)

Then convhex is called, just as usual.

Hopefully the whole script will be made public soon, we want to code-review it a bit more before :)

**Comment by fmckeogh** [comment]
That’s really helpful, thank you so much!
