### ISSUE TITLE
Need LibLoad Error

### ISSUE THREAD

**Issue by AlienKevin** [TI-Planet/Project-Builder#2]
When I started using keypad functions, PB throws a "Need LibLoad" error.

Link to PB: https://tiplanet.org/pb/?id=241355_1579434893_301705c495&file=main.c

main.c
```c
/* Keep these headers */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <tice.h>

/* Standard headers */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <keypadc.h>

/* Function prototypes */
void PrintText(int8_t xpos, int8_t ypos, const char *text);

int main(void)
{
    /* Key variable */
    kb_key_t key;
    const char *erase_string = "     ";

    /* Clear the homescreen */
    os_ClrHome();

    /* Loop until 2nd is pressed */
    do
    {
        /* Update kb_Data */
        kb_Scan();

        key = kb_Data[7];

        /* Print the current arrow key input */
        PrintText(0, 0, key & kb_Down ? "Down" : erase_string);

        PrintText(0, 1, key & kb_Up ? "Up" : erase_string);

        PrintText(0, 2, key & kb_Left ? "Left" : erase_string);

        PrintText(0, 3, key & kb_Right ? "Right" : erase_string);

    } while (kb_Data[1] != kb_2nd);

    return 0;
}

/* Draw text on the homescreen at the given X/Y location */
void PrintText(int8_t xpos, int8_t ypos, const char *text)
{
    os_SetCursorPos(ypos, xpos);
    os_PutStrFull(text);
}
```

PS: Great work on the IDE, it's very neat!

**Comment by adriweb** [comment]
Actually, that's not related to the PB - the calc throws that error, and for good reason :)
For any C program that needs libraries (GraphX, KeypadC etc.), you need to first have said libraries on calc. All programs share the libraries so you really only need to install them once (and from time to time update them), not for each program you make/get.

So:
1. Download the `clibs.8xg` file from the latest release: https://github.com/CE-Programming/libraries/releases/latest
2. Transfer that file with [TI Connect CE](https://education.ti.com/en/products/computer-software/ti-connect-ce-sw) or TILP.

Then whatever programs requiring LibLoad should work.

**Comment by AlienKevin** [comment]
I see. However, I can't find a way to load `clibs.8xg` onto the web IDE on PB?

**Comment by adriweb** [comment]
You can simply click on the "TI file(s)" button below the emulator and select the 8xg file.

![](https://i.imgur.com/CrRmdKw.png)

**Comment by AlienKevin** [comment]
Awesome. Thanks!
